services:
    expo:
        build: .
        image: tanveer/expo-management:latest
        command: ["java", "-Dspring.profiles.active=prod", "-jar", "expo-management.jar"]
        restart: always
        ports:
            - "8080:8080"
        environment:
            - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
            - DB_URL=${DB_URL}
            - DB_USERNAME=${DB_USERNAME}
            - DB_PASSWORD=${DB_PASSWORD}
            - MAIL_USERNAME=${MAIL_USERNAME}
            - MAIL_PASSWORD=${MAIL_PASSWORD}
            - ENCODER_SECRET=${ENCODER_SECRET}
            - ENCODER_IV=${ENCODER_IV}
            - ADMIN_PHONE=${ADMIN_PHONE}
            - ADMIN_EMAIL=${ADMIN_EMAIL}
            - ADMIN_PASSWORD=${ADMIN_PASSWORD}
        depends_on:
            mysql:
                condition: service_healthy
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "5"
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
            interval: 30s
            timeout: 5s
            retries: 3

    mysql:
        image: mysql:8.0
        restart: always
        environment:
            MYSQL_DATABASE: ${DB_NAME}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
        ports:
            - "3306:3306"
        volumes:
            - mysql-data:/var/lib/mysql
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            interval: 10s
            timeout: 5s
            retries: 5

volumes:
    mysql-data:
