spring:
    servlet:
        multipart:
            enabled: true
            location: ${java.io.tmpdir}
            max-file-size: 3MB
            max-request-size: 3MB

application:
    security:
        jwt:
            secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
            expiration: 86400000 # 1 day
            refresh-token:
                expiration: 604800000 # 7 days

    customCipherConfig:
        encoder:
            secret: 01$3456789A4C71#
            iv: 01$3456789A4C71#


logging:
    level:
        root: INFO
        com.betafore.evoting: DEBUG
    pattern:
        console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36}.%M - %msg%n"
